config/routes.rb
FajnyLink::Application.routes.draw do
  
  resources :links do
    resources :comments
    collection do
      get :tags
    end
  end

  devise_for :users

  resources :users do
    resources :links
  end

  root :to => "links#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :link
  attr_accessible :body, :user, :link
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :user
  has_many :comments, :dependent => :destroy
  attr_accessible :title, :url, :body, :user, :tag_list, :count, :private

  acts_as_taggable_on :tags
  ActsAsTaggableOn::TagList.delimiter = " "

  def self.search(search)
    if search
      where('title LIKE ? or body LIKE ?', "%#{search}%", "%#{search}")
    else
      scoped
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :lockable, :timeoutable and :activatable
  devise :database_authenticatable, :registerable, #:confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :links, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :email, :password, :password_confirmation

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/comments_controller.rb
# -*- coding: utf-8 -*-
class CommentsController < ApplicationController
  before_filter :authenticate_user!, :only => [:new, :create]
  before_filter :authorize_user_destroy, :only => [:destroy]
  def create
    @link = Link.find(params[:link_id])
    @comment = @link.comments.create(params[:comment])
    @comment.user = current_user
    @comment.link = @link
    @comment.save
    redirect_to link_path(@link)
  end

  def destroy
    @comment.destroy
    redirect_to link_path(@link)
  end

  protected

  def authorize_user_destroy
    @link = Link.find(params[:link_id])
    @comment = @link.comments.find(params[:id])
    if @comment.user != current_user
      redirect_to link_path(@link)
      flash[:notice] = "Brak uprawnień."
    end
  end

end

app/controllers/links_controller.rb
# -*- coding: utf-8 -*-
class LinksController < ApplicationController
  helper_method :sort_column, :sort_direction # +
  
  before_filter :authorize_user_read, :except => [:show, :index, :new, :create, :tags]  
  before_filter :authenticate_user!, :only => [:new, :create]

  before_filter :only => [:index, :tags] do
    @tags = Link.where(:private => false).tag_counts  # for tag clouds    
  end

  def index
    # @links = Link.all
    @links = Link.search(params[:search]).where(:private => false).order(sort_column + " " + sort_direction).paginate(:per_page => 5, :page => params[:page]) # +
  end

  def show
    @link = Link.find(params[:id])
  end

  def new
    @link = Link.new
  end

  def create
    @link = Link.new(params[:link])
    @link.user = current_user
    if @link.save
      flash[:notice] = "Successfully created link."
      redirect_to @link
    else
      render :action => 'new'
    end
  end

  def edit
    @link = Link.find(params[:id])
  end

  def update
    @link = Link.find(params[:id])
    if @link.update_attributes(params[:link])
      flash[:notice] = "Successfully updated link."
      redirect_to @link
    else
      render :action => 'edit'
    end
  end

  def destroy
    @link = Link.find(params[:id])
    @link.destroy
    flash[:notice] = "Successfully destroyed link."
    redirect_to links_url
  end

  def tags
    @links = Link.tagged_with(params[:name]).search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 5, :page => params[:page])
    render 'index'
  end


  protected

  def authorize_user_read
    @link = Link.find(params[:id])
    if @link.user != current_user
      redirect_to links_url
      flash[:notice] = "Brak uprawnień."
    end
  end

  private # +
  
  def sort_column # +
     Link.column_names.include?(params[:sort]) ? params[:sort] : "title" # +
  end # +
    
  def sort_direction # +
     %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc" # +
  end # +



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  helper_method :sort_column, :sort_direction
  
 before_filter do
    @user = current_user
  end

  def show
    @links = @user.links.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 5, :page => params[:page])
  end
  private # +
  
  def sort_column # +
     Link.column_names.include?(params[:sort]) ? params[:sort] : "title" # +
  end # +
    
  def sort_direction # +
     %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc" # +
  end # +
end

app/helpers/application_helper.rb
module ApplicationHelper

def sortable(column, title = nil)
  title ||= column.titleize
  css_class = column == sort_column ? "current #{sort_direction}" : nil
  direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
  link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
  include ActsAsTaggableOn::TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html>
<head>
  <title>FajnyLink</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<div id="ramka">
  <div id="nazwa">FajnyLink</div>
</div>
<div id="ramka2">
  <div id="nav">
    <p>			
	<a><%= link_to "Strona Glowna", links_path %></a> |
	<a href="">Kategorie</a> |
	<a href="">Top</a> 
    </p>
  </div>	
  <div id="info">
    Witaj na stronie! <script src="http://szabloniki.com/skrypty/pobierz.php?id=dzis" type=""></script> <script src="http://szabloniki.com/skrypty/pobierz.php?id=imieniny" type=""></script>
  </div>
</div>			
<div id="wrapper">	
  <div id="l_menu">		
    <% if user_signed_in? %>  
     Zalogowany jako <%= current_user.email %>.<br/>
     Nie Ty?  
     <%= link_to "Wyloguj", destroy_user_session_path %>
     <p id="dodaj_moje_linki"><%= link_to "Dodaj FajnyLink", new_link_path %></p>
     <p id="dodaj_moje_linki"><%= link_to "Moje linki", current_user %></p>
    <% else %>  
     <%= link_to "Rejestracja", new_user_registration_path %> albo  
     <%= link_to "Zaloguj", new_user_session_path %>  
    <% end %> 		
    <br/><br/><br/><br/>		
    <center>	
      <%= form_tag links_path, :method => 'get', :id => "links_search" do %> 
      <p>
	<%= hidden_field_tag :direction, params[:direction] %>
	<%= hidden_field_tag :sort, params[:sort] %>
	<%= text_field_tag :search, params[:search], :size => 10 %>
	<%= submit_tag "Szukanie", :title => nil %>
      </p>  
      <% end %>
    </center>
  </div>
  <div id="content">
    <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>
    <div id="user_nav">  	
    </div>
    <%= yield %>
  </div>
</div>
<div id="foot">
Copyright by adresstrony.pl | Szablon wykonała <a href="http://szabloniki.com" title="szablony">Sliffka</a>
</div>


</body>
</html>

app/views/links/_form.html.erb
<%= form_for @link do |f| %>
  <p>
    Tytuł linka:<br />
    <%= f.text_field :title %>
  </p>
  <p>
    Url linka:<br />
    <%= f.text_field :url %>
  </p>
  <p>
     Czy link ma być prywatny?: <br />
    <%= f.check_box :private %>
  </p>
  <p>
    Opis linka:<br />
    <%= f.text_area :body, :cols => 30, :rows => 5 %>
  </p>

  <p>
    Lista tagów: <br />
	<%= f.text_field :tag_list %> 
  </p>
  
  <p><%= f.submit %></p>
<% end %>

app/views/links/_index.html.erb
<table class="pretty">
  <tr>
	  <!-- atrubut sortowania -->	  
    <th><%= sortable "title", "Tytuł" %></th>
    <th><%= sortable "url", "Url" %></th>
    <th><%= sortable "body", "Opis" %></th>
  </tr>
</table>

<br/><br/>

 <% for link in @links %>
<table id="linki">
    <tr id="glosuj_data"> 
      <td id="ocena">w góre / w dól</td>
      <td id="data">data: <%= link.created_at %></td>
   </tr>
   <tr>
	<th COLSPAN=2 id="user_name"> <%= link.user.username %></th>
   </tr>
   <tr>
      <th COLSPAN=2 id="tytul"><%= link.title %></th>    
   </tr> 
   <tr>    
      <td COLSPAN=2 id="url"><a href="<%= link.url %>"><%= link.url %></a></td>
   </tr>
   <tr id="opis">
      <td><%= link.body %></td>
   </tr>
   <tr id="ocena_komentarz">
      <td> ocena: 15 </td>
      <td id="kom">  <%= link_to "Komentarze", link %> (<%= link.comments.length %>) </td>
   </tr>
	</table>
	<br/><br/>
  <% end %>


<%= will_paginate @links %>

app/views/links/edit.html.erb
<%= render 'form' %>

<p>
  <%= link_to "Powrót do wszystkich", links_path %>
</p>

app/views/links/index.html.erb
<div id="links"><%= render 'index' %></div>

<% tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class| %>
<%= link_to tag.name, tags_links_path(:name=>tag.name), :class => css_class %>
<% end %>

app/views/links/index.js.erb
$("#links").html("<%= escape_javascript(render('index')) %>");

app/views/links/new.html.erb
<%= render 'form' %>

<p><%= link_to "Powrót do wszystkich", links_path %></p>

app/views/links/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @link.title %>
</p>
<p>
  <strong>Url:</strong>
  <%= @link.url %>
</p>
<p>
  <strong>Body:</strong>
  <%= @link.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @link.user.username %>
</p> 
<p>
  Tagi: <%= @link.tag_list %>
</p>

<h2>Komentarze :</h2>

<% @link.comments.each do |comment| %>
<div id="komentarze">
  <p>
    <b>Komentator:</b>
    <%= comment.user.username %>
  </p>
 
  <p>
    <b>Komentarz:</b>
    <%= comment.body %>
  </p>

  <% if comment.user == current_user %>
  <p>
  <%= link_to 'Usuń komentarz', [@link, comment],
               :confirm => 'Napewno?',
               :method => :delete %>
  </p>
  </div>
  <br/><br/>
  
  <% end %>
<% end %>



<% if user_signed_in? %>
  <h2>Dodaj komentarz:</h2>
  <%= form_for([@link, @link.comments.build]) do |f| %>
    <div class="field">
      Treść:<br />
      <%= f.text_area :body, :rows => 5, :columns => 5 %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
<% else %>
  <h2>Trzeba być zalogowanym by móc komentować wpisy.</h2>
<% end %>

<% if @link.user == current_user %>
<p>
  <%= link_to "Edytuj", edit_link_path(@link) %> |
  <%= link_to "Usuń", @link, :confirm => 'Napewno?', :method => :delete %> |
  <%= link_to "Pokaż wszystkie", links_path %>
</p>
<% else %>
<p>
  <%= link_to "Pokaż wszystkie", links_path %>
</p>  
<% end %>

app/views/users/show.html.erb
<table class="pretty">
  <tr>
	  <!-- atrubut sortowania -->	  
    <th><%= sortable "title", "Tytuł" %></th>
    <th><%= sortable "url", "Url" %></th>
    <th><%= sortable "body", "Opis" %></th>
  </tr>
</table>

<br/><br/>

 <% for link in @links %>
<table id="linki">
    <tr id="glosuj_data"> 
      <td id="ocena">w góre / w dól</td>
      <td id="data">data: <%= link.created_at %></td>
   </tr>
   <tr>
	<th COLSPAN=2 id="user_name"> <%= link.user.username %></th>
   </tr>
   <tr>
      <th COLSPAN=2 id="tytul"><%= link.title %></th>    
   </tr>
   <tr>    
      <td COLSPAN=2 id="url"><a href="<%= link.url %>"><%= link.url %></a></td>
   </tr>
   <tr id="opis">
      <td><%= link.body %></td>
   </tr>
   <tr id="ocena_komentarz">
      <td> ocena: 15 </td>
      <td id="kom"> <%= link_to "Komentarze", link %> (<%= link.comments.length %>) </td>
   </tr>
   <tr>
      <td><%= link_to "Pokaż", link %></td>
      <td><%= link_to "Edytuj", edit_link_path(link) %></td>
      <td><%= link_to "Usuń", link, :confirm => 'Napewno?', :method => :delete %></td>
   </tr>
</table>
	
<% end %>
<br/><br/>

<%= will_paginate @links %>